name: XAuto
options:
  bundleIdPrefix: com.xauto
  deploymentTarget:
    iOS: '17.0'
settings:
  base:
    SWIFT_VERSION: 5.10
packages: {}

targets:
  XAutoApp:
    type: application
    platform: iOS
    sources:
      - Sources/XAutoApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xauto.app
        INFOPLIST_FILE: Sources/XAutoApp/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - target: XAutoWidget
        embed: true

  XAutoWidget:
    type: app-extension
    platform: iOS
    sources:
      - Sources/XAutoWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xauto.widget
        INFOPLIST_FILE: Sources/XAutoWidget/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
