name: XAuto
options:
  bundleIdPrefix: com.xauto
  deploymentTarget:
    iOS: '26.0'
settings:
  base:
    SWIFT_VERSION: 5.10
packages:
  Atributika:
    url: https://github.com/psharanda/Atributika.git
    from: 5.0.0
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.4.1

schemes:
  XAutoApp:
    build:
      targets:
        XAutoApp: all
        XAutoWidget: [build]
    test:
      config: Debug
      testPlans:
        - path: XAutoPR.xctestplan
          defaultPlan: true
        - path: XAutoFull.xctestplan
    run:
      config: Debug
    archive:
      config: Release

targets:
  XAutoApp:
    type: application
    platform: iOS
    sources:
      - Sources/XAutoApp
      - Sources/XAutoShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xauto.ai
        INFOPLIST_FILE: Sources/XAutoApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Sources/XAutoApp/XAutoApp.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: NKTXY2K9WD
    dependencies:
      - package: Atributika
        product: Atributika
      - package: Atributika
        product: AtributikaViews
      - package: MarkdownUI
        product: MarkdownUI
      - target: XAutoWidget
        embed: true

  XAutoWidget:
    type: app-extension
    platform: iOS
    sources:
      - Sources/XAutoWidget
      - Sources/XAutoShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xauto.ai.widget
        INFOPLIST_FILE: Sources/XAutoWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/XAutoWidget/XAutoWidget.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: NKTXY2K9WD

  XAutoAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Sources/XAutoAppTests
    dependencies:
      - target: XAutoApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xauto.ai.tests
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: NKTXY2K9WD

  XAutoAppUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - Sources/XAutoAppUITests
    dependencies:
      - target: XAutoApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xauto.ai.uitests
        GENERATE_INFOPLIST_FILE: YES
        TEST_TARGET_NAME: XAutoApp
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: NKTXY2K9WD
