name: XAuto
options:
  bundleIdPrefix: com.xauto
  deploymentTarget:
    iOS: '17.0'
settings:
  base:
    SWIFT_VERSION: 5.10
packages: {}

schemes:
  XAutoApp:
    build:
      targets:
        XAutoApp: all
        XAutoWidget: [build]
    run:
      config: Debug
    archive:
      config: Release

targets:
  XAutoApp:
    type: application
    platform: iOS
    sources:
      - Sources/XAutoApp
      - Sources/XAutoShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xauto.app
        INFOPLIST_FILE: Sources/XAutoApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Sources/XAutoApp/XAutoApp.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - target: XAutoWidget
        embed: true

  XAutoWidget:
    type: app-extension
    platform: iOS
    sources:
      - Sources/XAutoWidget
      - Sources/XAutoShared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xauto.app.widget
        INFOPLIST_FILE: Sources/XAutoWidget/Info.plist
        CODE_SIGN_ENTITLEMENTS: Sources/XAutoWidget/XAutoWidget.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
